### ISSUE TITLE
Disk space preventive maintenance

### ISSUE THREAD

**Issue by warrenca** [microservices-today/IaC-wrapper#41]
Failed to images due to jenkins slave having out of space.
Failed to write log files due to insufficient disk space.

- Clean up unused images and containers
- Mount or allot a bigger disk storage to /var/lib/docker (This is where the mesos-cloud jenkins slave is building all jobs including `docker build`)

**Comment by kamoljan** [comment]
@warrenca thank you for your feedback. 
It will be solved with next release.

**Comment by kamoljan** [comment]
@warrenca this issue was solved with [dfc11e5](https://github.com/microservices-today/IaC-wrapper/commit/dfc11e54796c4bc2c87affcb13fe24bec164f95e) commit. Going to close this issue.
